version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
